Feature/5 expense api
TheKiddos/expensia pull request #13
Opened 2021-11-05 08:28 UTC by Mouiad-JRA

2021-11-05 09:04 UTC, HHHMHA requested changes

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/admin.py
> +    def has_add_permission(self, request, obj=None):
not needed

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/admin.py
> +    def get_list_display(self, request):
not needed

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/models.py
> +    start_date = models.DateTimeField(_("Start Date"), null=False, blank=False)
Expense just has a creation date no need for start and end date here.
Just inherit from `TimeStampedModel`

Don't forget to remove these two fields in other places.
Also delete the migration and create another one

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/models.py
> +    def get_categories(self):
Each expense has one category so what does this method do?

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/views.py
> +    def get_serializer_context(self):
Not needed

2021-11-05 09:04 UTC, HHHMHA commented on backend/expensia/expense/views.py
> +    filter_fields = ("start_date", "end_date")
These will become custom filtering
you can create a FilterClass for them or do it manually in the `filter_queryset `method

2021-11-05 09:04 UTC, HHHMHA commented on backend/requirements/base.txt
> +# Django
Not needed also not updated

2021-11-06 18:03 UTC, Mouiad-JRA commented
Don't fuck with me , Fix the plugin error  and update the req

2021-11-06 21:03 UTC, HHHMHA approved these changes

2021-11-06 21:04 UTC, merged